export const BONUS = [
  {
    id: 0,
    content: "Area de",
    title: `O que nós esperamos de você esuas experiências`,
    desciption: `Pesquisando de forma anónica os trabalhos em seguida.`,
    avatar: "/bonus/image-1.png",
    employeeType: "CEO",
    name: "Speak With Us",
  },
  {
    id: 1,
    content: "Area de",
    title: `O que nós esperamos de você esuas experiências`,
    desciption: `Pesquisando de forma anónica os trabalhos em seguida.`,
    avatar: "/bonus/image-2.png",
    employeeType: "CEO",
    name: "Telecon",
  },
  {
    id: 2,
    content: "Area de",
    title: `O que nós esperamos de você esuas experiências`,
    desciption: `Pesquisando de forma anónica os trabalhos em seguida.`,
    avatar: "/bonus/image-3.png",
    employeeType: "CTO",
    name: "Kiari Code",
  },
  {
    id: 3,
    content: "Area de",
    title: `O que nós esperamos de você esuas experiências`,
    desciption: `Pesquisando de forma anónica os trabalhos em seguida.`,
    avatar: "/bonus/image-4.png",
    employeeType: "CEO",
    name: "Dream Yetu",
  },
  {
    id: 4,
    content: "Area de",
    title: `O que nós esperamos de você esuas experiências`,
    desciption: `Pesquisando de forma anónica os trabalhos em seguida.`,
    avatar: "/bonus/image-5.png",
    employeeType: "CEO",
    name: "Speak With Us",
  },
];
